import Fixture from '../models/fixtures'

// Constructing each fixture in an array
const fixtures = [
    new Fixture({
        _id: '5d4155cfcd68f4086d8df460',
        homeTeam: 'Chelsea',
        awayTeam: 'Liverpool',
        homeGoals: 2,
        awayGoals: 1,
        matchTime: new Date(2019, 8, 10, 2, 30, 20),
        stadium: 'Stamford Bridge, London',
        referee: 'Hilton Gate',
        isPlayed: true,
        Attendance: '140000',
    }),
    new Fixture({
        _id: '5d4155cfcd68f4086d8df461',
        homeTeam: 'Southampton',
        awayTeam: 'AFC Bournemouth',
        homeGoals: 0,
        awayGoals: 0,
        matchTime: new Date(2019, 9, 20, 3, 30, 25),
        stadium: "St. Mary's Stadium, Southampton",
        referee: 'Howard Bate',
        isPlayed: false,
    }),
    new Fixture({
        _id: '5d4155cfcd68f4086d8df462',
        homeTeam: 'Arsenal',
        awayTeam: 'Aston Villa',
        homeGoals: 0,
        awayGoals: 0,
        matchTime: new Date(2019, 9, 22, 3, 30, 25),
        stadium: 'Emirates Stadium, London',
        referee: 'Hilton Gate',
        isPlayed: false,
    }),
    new Fixture({
        _id: '5d4155cfcd68f4086d8df463',
        homeTeam: 'West Ham United',
        awayTeam: 'Manchester United',
        homeGoals: 0,
        awayGoals: 0,
        matchTime: new Date(2019, 9, 22, 3, 30, 25),
        stadium: 'London Stadium, London',
        referee: 'Hilton Gate',
        isPlayed: false,
    }),
    new Fixture({
        _id: '5d4155cfcd68f4086d8df465',
        homeTeam: 'Tottenham Hotspur',
        awayTeam: 'Crystal Palace',
        homeGoals: 4,
        awayGoals: 0,
        matchTime: new Date(2019, 9, 14, 6, 30, 0),
        stadium: 'Tottenham Hotspur Stadium, London',
        referee: 'Adam Brown',
        isPlayed: true,
        Attendance: '59812',
    }),
    new Fixture({
        _id: '5d4155cfcd68f4086d8df466',
        homeTeam: 'AFC Bournemouth',
        awayTeam: 'Everton',
        homeGoals: 3,
        awayGoals: 1,
        matchTime: new Date(2019, 9, 15, 10, 30, 0),
        stadium: 'Vitality Stadium, Bournemouth',
        referee: 'Eager Thompson',
        isPlayed: true,
        Attendance: '10416',
    }),
]

export default fixtures
